version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directories:
      - "/scripts/step03_explore_examples/01_naive_rag/"
      - "/scripts/step03_explore_examples/utils/"
    schedule:
      interval: "weekly"
    target-branch: "refactor/step02"
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly    
