[tool.poetry]
name = "advanced-rag"
version = "0.1.0"
description = "Demonstration of different Advanced RAG techniques"
authors = ["SeriousSem"]
readme = "README.md"
packages = [{ include = "src" }, { include = "helpers" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
generative-ai-hub-sdk = {extras = ["all"], version = "^4.12.4"}
python-dotenv = "^1.0.1"
utils = { path = "../utils", develop = true }
gitpython = "^3.1.43"
pymupdf = "^1.24.7"
lark = "^1.2.2"
langchain-hana = "^0.2.1"
pydantic = "^2.10.6"
langchain-experimental = "^0.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"