[tool.poetry]
name = "utils"
version = "0.1.4"
description = "Utils for exploring examples"
authors = ["romaniam"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
python-dotenv = "^1.0.1"
generative-ai-hub-sdk = {extras = ["all"], version = "^4.12.4"}
hdbcli = "^2.24.26"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
