[tool.poetry]
name = "rag-on-mixed-data"
version = "0.1.0"
description = "Examples showing RAG examples on structured and unstructured data"
authors = ["EvgeniiSkrebtcov"]
readme = "README.md"
packages = [{ include = "library" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
generative-ai-hub-sdk = {extras = ["all"], version = "^4.12.4"}
python-dotenv = "^1.0.1"
utils = { path = "../utils", develop = true }
wikipedia = "^1.4.0"
langchain-hana = "^0.2.1"
sqlalchemy-hana = "^3.0.3"
sqlalchemy = "^2.0.41"
hdbcli = "^2.24.26"
poetry = "^2.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
